### ISSUE TITLE
gunicorn proxy bad gateway 502 redirect?

### ISSUE THREAD

**Issue by ArashTajalli** [nebhead/garage-zero#1] opened 2019-03-02 20:37 UTC
Hey there this is my first git anything to keep in mind a bit of noobiness that may come along the way but, I'm trying to figure out the problem with what I think is Gunicorn not being setup correctly to proxy for NGINX. I've followed the directions to the Tee, I even flashed my SD card with a blank slate. But I keep getting stuck at a 502 Bad Gateway and I've confirmed that my routers and firewalls aren't blocking the ports. The config files are all working fine and services are also healthy and running and ps aux shows them working.

> 2019/03/02 15:20:57 [error] 13533#13533: *1 connect() failed (111: Connection refused) while connecting to upstream, client: IP-hidden, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "IP-hidden"

certain IP addresses hidden for my ofwn protection

Part of it is working with me being able to access the client IP:9001 and getting those 2 controls. So I know the project isn't at a total loss for me.

BTW The project altogether looks great! it's been a real joy getting comprehensive instructions and the hardware stuff :D

2 hours later?:
the /etc/nginx/{sites-enabled, sites-available}/garage-zero files were missing a "garage zero" right next to "location /"

So
```
server {
    location ~/garage-zero {
        ...
    }
}

```

However now I'm greeted with a "welcome to nginx!" which is a sight for sore eyes after so much config scouring.

**Comment by nebhead** [comment] 2019-03-02 23:13
Very strange... when you try your pi's IP at port 5000, what do you see?

**Comment by nebhead** [comment] 2019-03-02 23:18
Also, your sites-enabled/available file should look more like this: 

`server {
    location / {
		proxy_pass http://127.0.0.1:8000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}
`

**Comment by nebhead** [comment] 2019-03-02 23:23
Also, try port 8000.  So, try:

your.pi.ip.address:5000
your.pi.ip.address:8000

If either of those is working then your Flask app.py is running ok, but perhaps we need to go back to nginx and see what's going on there.

**Comment by ArashTajalli** [comment] 2019-03-03 08:52
In your second comment that compares mine I was shorthanding it due to rebooting the pi, the only difference really was:
 
>location / {
#gives me the 502 bad gateway
>location ~/garage-zero {
#gives me the "welcome to Nginx" page

Entering the 5000 and 8000 ports I've gotten nothing in the web browser: Firefox prompt "unable to connect" Which surprises me that it doesn't work because I made sure pip did install flask with sudo.

I am considering making an image of this SD card back it up on my HDD and reflash it again with a fresh lite install so I can start from zero once more. (Hell I'll make a private youtube video so I don't look insane) Thanks for keeping up with this thread

Originally I thought there were some public IPs in here but it looks like I'll be fine sharing logs about devices within my local network.

![bad gateway](https://user-images.githubusercontent.com/22821896/53693010-6fe95800-3d67-11e9-8505-fb8e7b618f0c.png)

**Comment by nebhead** [comment] 2019-03-03 17:23
Oh it's no problem, I am just really happy someone is using my little project. :)

So, since this appears to be an nginx proxy type issue, maybe let's try to nuke nginx and re-install. 

`sudo apt purge nginx nginx-common # Removes everything`

At this point you might test accessing the gunicorn/flask application directly again by going to 10.0.0.22:8000.  But honestly, you can probably go straight to reinstalling nginx.  

`sudo apt install nginx -y`

Then do the nginx config again:

```
# Make sure you're in the right directory
cd ~/garage-zero

# Delete default configuration
sudo rm /etc/nginx/sites-enabled/default

# Copy configuration file to nginx
sudo cp garage-zero.nginx /etc/nginx/sites-available/garage-zero

# Create link in sites-enabled
sudo ln -s /etc/nginx/sites-available/garage-zero /etc/nginx/sites-enabled

# Restart nginx
sudo service nginx restart
```

After all this, give it another try (or reboot first and try again).  

I'm going to walk through the install process again on a pi that I have laying around myself to confirm.  It's possible that something has changed in a newer version of raspbian, or nginx that is goofing things up.  And I really like your idea of making a video - that might be something I add to this project as a walkthrough / tutorial.

**Comment by nebhead** [comment] 2019-03-04 00:23
Well, after running through my own instructions, it seems I have exactly the same error.  My issue appears to be one with Flask and Gunicorn though.  I will need to debug a bit more, but thanks for pointing this out.  I'll post an update when I have a chance to get to the bottom of this.

**Comment by ArashTajalli** [comment] 2019-03-04 00:39
Much appreciated! I'm certain its the same issue between us. I didn't bring my pi with me to test it out during my travels, but if I happen to dig around and successfully solve it myself I'll branch the project. And I'm glad you put it up! We all learn in this process of testing and deploying and I've come to learn a lot more about these newer tools.

I've put off the same project for so long and finally got the time to see if others like you have made a modern-ish solution compared to my lamp stack solution that I can't remember what I did. anyways cheers I hope the solution comes to you sooner than later. o/

**Comment by nebhead** [comment] 2019-03-04 06:27
Figured it out!  

Somehow, I had inserted an error into my webapp.conf file for supervisord.  Basically, the way that I was launching gunicorn (using an explicit path to the app in the command) was causing gunicorn to crash.  Supervisor was trying to restart the app over and over, but to no avail.  Anyway, nginx will throw up a bad gateway when there is nothing handling the requests - and in this case since gunicorn was crashing it wasn't responding.  

So the fix is to change the following line in the webapp.conf file in /etc/supervisor/conf.d/ directory from: 
`command=/usr/bin/gunicorn /home/pi/garage-zero/app:app`
to:
`command=/usr/bin/gunicorn app:app`
And after a reboot, you should be golden.  

I'm working on updating the git repo with this change, as well as a few modifications to the documentation that I found along the way.  I did want to sincerely thank you for bringing this to my attention.  I wouldn't have found this or fixed it without you calling it out.  Give this a try and let me know how it goes.  I'll close this issue once you've confirmed it.  Thanks again!

**Comment by ArashTajalli** [comment] 2019-03-05 10:54
Guh Sweet release, you've certainly done a great job and have helped me and others who stumbled onto this project, cheers man!

![2019-03-05 05_45_44-garage door app](https://user-images.githubusercontent.com/22821896/53800104-f6d63600-3f09-11e9-8b5b-ccbd91769dfe.png)

**Comment by nebhead** [comment] 2019-03-05 15:21
You are welcome!  Thanks for making it better, and thanks for giving it a try!

**Closed by nebhead** 2019-03-05 15:21 UTC
